# Book Two {- #book-2}

## 1 {-#1}

Begin the morning by saying to yourself, I will encounter busybodies, the ungrateful, arrogant, deceitful, envious, and unsociable. All these things happen to them because of their ignorance of what is good and evil. But I, who have seen the nature of the good, that it is beautiful, and of the bad, that it is ugly, and the nature of the one who does wrong, that he is related to me, not only of the same blood or lineage, but that he shares the same intelligence and the same divine spark, I can neither be harmed by any of them, for no one can inflict ugliness upon me, nor can I be angry with my kin, nor hate him, for we are made for cooperation, like feet, like hands, like eyelids, like the rows of upper and lower teeth. To act against one another, then, is contrary to nature; and being annoyed and turning away is acting against one another.

## 2 {-#2}

Whatever this is that I am, it is a little flesh and breath, and the ruling part. Throw away your books; no longer distract yourself: it is not allowed; but as if you were now dying, despise the flesh; it is blood and bones, an interweaving of nerves, veins, and arteries. See the breath also, what kind of a thing it is—air, and not always the same, but every moment sent out and again drawn in. The third, then, is the ruling part: consider this: You are an old man; no longer let this be a slave, no longer be pulled by the strings like a puppet towards unsocial movements, no longer either be dissatisfied with your present lot, or shrink from the future.

## 3 {-#3}

All that comes from the gods is full of Providence. That which comes from fortune is not separated from nature or without an interweaving and entanglement with the things ordered by Providence. From there, all things flow; and there is besides necessity, and that which is for the advantage of the whole universe, of which you are a part. But that is good for every part of nature which the nature of the whole brings, and what serves to maintain this nature. Now the universe is preserved, as by the changes of the elements, so by the changes of things compounded of the elements. Let these principles be enough for you; let them always be fixed opinions. But cast away the thirst for books, so that you may not die murmuring, but cheerfully, truly, and from your heart thankful to the gods.

## 4 {-#4}

Remember how long you have been putting off these things, and how often you have received an opportunity from the gods, and yet do not use it. You must now at last perceive of what universe you are a part, and of what administrator of the universe your existence is an emanation, and that a limit of time is fixed for you, which if you do not use for clearing away the clouds from your mind, it will pass and you will pass, and it will never return.

## 5 {-#5}

Every moment, think steadily as a Roman and a man to do what you have in hand with perfect and simple dignity, and a feeling of affection, and freedom, and justice; and to relieve yourself from all other thoughts. And you will find relief if you do every act of your life as if it were the last, laying aside all carelessness and passionate aversion from the commands of reason, and all hypocrisy, and self-love, and discontent with the portion which has been given to you. You see how few the things are that, if a man grasps them, he is able to live a life that flows in quiet, and is like the existence of the gods; for the gods, on their part, will require nothing more from him who observes these things.

## 6 {-#6}

Do wrong to yourself, do wrong to yourself, my soul; but you will no longer have the opportunity of honoring yourself. Every man's life is sufficient. But yours is nearly finished, though your soul does not reverence itself but places your happiness in the souls of others.

## 7 {-#7}

Do the external things that happen to you distract you? Give yourself time to learn something new and good, and cease to be whirled around. But then you must also avoid being carried about in the other way. For those too are triflers who have wearied themselves in life by their activity, and yet have no object to which to direct every movement, and, in a word, all their thoughts.

## 8 {-#8}

A man has seldom been seen to be unhappy through not observing what is in another's mind; but those who do not observe the movements of their own minds must necessarily be unhappy.

## 9 {-#9}

This you must always bear in mind: what is the nature of the whole, and what is your nature, and how this is related to that, and what kind of a part it is of what kind of a whole; and that there is no one who hinders you from always doing and saying the things which are according to the nature of which you are a part.

## 10 {-#10}

Theophrastus, in his comparison of bad acts—a comparison such as one would make in accordance with the common notions of humanity—says, like a true philosopher, that the offenses committed through desire are more blameworthy than those committed through anger. For he who is excited by anger seems to turn away from reason with a certain pain and unconscious contraction; but he who offends through desire, being overpowered by pleasure, seems to be in a way more intemperate and lacking self-control in his offenses. Rightly then, and in a way worthy of philosophy, he said that the offense committed with pleasure is more blameworthy than that committed with pain; and on the whole, the one is more like a person who has been first wronged and through pain is compelled to be angry; but the other is moved by his own impulse to do wrong, being carried towards doing something by desire.

## 11 {-#11}

Since it is possible that you may depart from life this very moment, regulate every act and thought accordingly. But to depart from among men, if there are gods, is not a thing to be afraid of, for the gods will not involve you in evil; but if indeed they do not exist, or if they have no concern about human affairs, what is it to me to live in a universe devoid of gods or devoid of Providence? But in truth, they do exist, and they do care for human matters, and they have put all the means in human power to enable one not to fall into real evils. And as for the rest, if there was anything evil, they would have provided for this also, that it should be altogether in a person's power not to fall into it. Now that which does not make a person worse, how can it make a person's life worse? But neither through ignorance, nor having the knowledge but not the power to guard against or correct these things, is it possible that the nature of the universe has overlooked them; nor is it possible that it has made so great a mistake, either through lack of power or lack of skill, that good and evil should happen indiscriminately to the good and the bad. But death certainly, and life, honor and dishonor, pain and pleasure—all these things equally happen to good and bad people, being things which make us neither better nor worse. Therefore, they are neither good nor evil.

## 12 {-#12}

How quickly all things disappear—in the universe, the bodies themselves, but in time, the remembrance of them; what is the nature of all sensible things, and particularly those which attract with the bait of pleasure or terrify by pain, or are widely known through empty fame; how worthless, and contemptible, and sordid, and perishable, and dead they are—all this it is the part of the intellectual faculty to observe. To observe too who these are whose opinions and voices give reputation; what death is, and the fact that, if a person looks at it in itself, and by the abstractive power of reflection resolves into their parts all the things which present themselves to the imagination in it, he will then consider it to be nothing else than an operation of nature; and if anyone is afraid of an operation of nature, he is a child. This, however, is not only an operation of nature, but it is also a thing which contributes to the purposes of nature. To observe too how humanity comes near to the deity, and by what part of it, and when this part of humanity is so disposed.

## 13 {-#13}

Nothing is more wretched than a man who traverses everything in circles, and pries into the things beneath the earth, as the poet says, and seeks by conjecture what is in the minds of his neighbors, without perceiving that it is sufficient to attend to the inner guiding spirit within him, and to reverence it sincerely. And reverence of the inner guiding spirit consists in keeping it pure from passion and thoughtlessness, and dissatisfaction with what comes from gods and humanity. For the things from the gods merit veneration for their excellence; and the things from people should be dear to us because of kinship; and sometimes even, in a way, they move our pity because of people's ignorance of good and bad; this defect being no less than that which deprives us of the power of distinguishing things that are white and black.

## 14 {-#14}

Though you should be going to live three thousand years, and as many times ten thousand years, still remember that no one loses any other life than this which he now lives, nor lives any other than this which he now loses. The longest and shortest are thus brought to the same. For the present is the same to all, though that which perishes is not the same; and so that which is lost appears to be a mere moment. For one cannot lose either the past or the future: for what one does not have, how can anyone take this from him? These two things then you must bear in mind; the one, that all things from eternity are of like forms and come round in a circle, and that it makes no difference whether one shall see the same things during a hundred years or two hundred, or an infinite time; and the second, that the longest liver and he who will die soonest lose just the same. For the present is the only thing of which one can be deprived, if it is true that this is the only thing which he has, and that one cannot lose a thing if he has it not.

## 15 {-#15}

Remember that all is opinion. For what was said by the Cynic Monimus is evident: and evident too is the use of what was said, if a person receives what may be gained from it as far as it is true.

## 16 {-#16}

The human soul does violence to itself, first of all, when it becomes an abscess and, as it were, a tumor on the universe, as far as it can. For to be annoyed at anything which happens is a separation of ourselves from nature, in some part of which the natures of all other things are contained. Secondly, the soul does violence to itself when it turns away from any person, or even moves towards them with the intention of injuring, such as are the souls of those who are angry. Thirdly, the soul does violence to itself when it is overpowered by pleasure or by pain. Fourthly, when it plays a part, and does or says anything insincerely and untruthfully. Fifthly, when it allows any act of its own and any movement to be without an aim, and does anything thoughtlessly and without considering what it is, it being right that even the smallest things be done with reference to an end; and the end of rational animals is to follow the reason and the law of the most ancient city and state.

## 17 {-#17}

Of human life, time is a point, and substance is in a flux, and perception is dull, and the composition of the whole body is subject to decay, and the soul is a whirl, and fortune is hard to divine, and fame is a thing devoid of judgment. And, to say all in a word, everything which belongs to the body is a stream, and what belongs to the soul is a dream and vapor, and life is a warfare and a stranger's temporary stay, and after-fame is oblivion. What then is that which is able to guide a person? One thing and only one: philosophy. But this consists in keeping the inner guiding spirit within a person free from violence and unharmed, superior to pains and pleasures, doing nothing without purpose, nor yet falsely and with hypocrisy, not feeling the need of another person's doing or not doing anything; and besides, accepting all that happens, and all that is allotted, as coming from thence, wherever it is, from whence he himself came; and, finally, waiting for death with a cheerful mind, as being nothing else than a dissolution of the elements of which every living being is compounded. But if there is no harm to the elements themselves in each continually changing into another, why should one have any apprehension about the change and dissolution of all the elements? For it is according to nature, and nothing is evil which is according to nature.

This in Carnuntum.
