# Book Four {- #book-4}

## 1 {-#1}

The part of us that governs, when it's in line with nature, reacts to events in a way that always easily adapts to whatever happens and is presented to it. It doesn't need a specific type of situation, but it moves towards its purpose, albeit with certain conditions. It even creates its own opportunities from what opposes it, just as a fire consumes what falls into it. A small flame would be extinguished by it, but a strong fire quickly takes hold of the added material, burns it, and grows taller because of it.

## 2 {-#2}

Let no act be done without a purpose, nor otherwise than according to the perfect principles of skill.

## 3 {-#3}

People look for getaways: country houses, seashores, and mountains. You, too, often desire such things. But this is entirely typical of ordinary people, because you have the power to retreat into yourself whenever you choose. Nowhere can a person find more peace or more freedom from trouble than within their own soul, particularly when they have within them such thoughts that by simply looking into them they are immediately in perfect tranquility. I assert that tranquility is nothing more than a good ordering of the mind. So, constantly give yourself this retreat, and renew yourself. Let your principles be brief and fundamental; as soon as you turn to them, they will be enough to cleanse the soul completely and to send you back free from all discontent with the things to which you return. What are you discontented with? The badness of people? Recall to your mind this conclusion: that rational beings exist for one another, and that to endure is a part of justice, and that people do wrong unintentionally. And consider how many already, after mutual enmity, suspicion, hatred, and fighting, have been stretched dead, reduced to ashes; and be quiet at last.

But perhaps you're dissatisfied with what's been assigned to you by the universe. Recall to your recollection this alternative: either there is providence or atoms, a chance concurrence of things; or remember the arguments by which it has been proved that the world is a kind of political community, and be quiet at last.

But perhaps physical things will still bother you. Consider then further that the mind doesn't mix with the breath, whether moving gently or violently, when it has once drawn itself apart and discovered its own power. And think also of all that you've heard and assented to about pain and pleasure, and be quiet at last.

But perhaps the desire for what's called fame will torment you. See how soon everything is forgotten, and look at the chaos of infinite time on each side of the present, and the emptiness of applause, and the changeableness and lack of judgment in those who pretend to give praise, and the narrowness of the space within which it is confined, and be quiet at last. For the whole earth is a point, and how small a nook in it is this your dwelling, and how few are there in it, and what kind of people are they who will praise you.

This then remains: Remember to retire into this little territory of your own, and above all do not distract or strain yourself, but be free, and look at things as a man, as a human being, as a citizen, as a mortal. But among the things readiest to your hand to which you shall turn, let there be these two. One is that things do not touch the soul, for they are external and remain unmoving; but our disturbances come only from the opinion which is within. The other is that all these things, which you see, change immediately and will no longer be; and constantly bear in mind how many of these changes you have already witnessed. The universe is transformation: life is opinion.

## 4 {-#4}

If our intellectual part is common, the reason also, in respect of which we are rational beings, is common. If this is so, common also is the reason which commands us what to do and what not to do. If this is so, there is a common law also. If this is so, we are fellow-citizens. If this is so, we are members of some political community. If this is so, the world is in a manner a state. For of what other common political community will anyone say that the whole human race are members? And from there, from this common political community, comes also our very intellectual faculty and reasoning faculty and our capacity for law. Or whence do they come? For as my earthly part is a portion given to me from certain earth, and that which is watery from another element, and that which is hot and fiery from some peculiar source (for nothing comes out of nothing, as nothing also returns to non-existence), so also the intellectual part comes from some source.

## 5 {-#5}

Death is such as generation is, a mystery of nature; a composition out of the same elements, and a decomposition into the same. And altogether not a thing of which any person should be ashamed, for it is not contrary to the nature of a reasonable animal, and not contrary to the reason of our constitution.

## 6 {-#6}

It is natural that these things should be done by such persons; it is a matter of necessity. And if a person will not have it so, he will not allow the fig-tree to have juice. But by all means bear this in mind, that within a very short time both you and he will be dead; and soon not even your names will be left behind.

## 7 {-#7}

Take away your opinion, and then the complaint, "I have been harmed," is taken away. Take away the complaint, "I have been harmed," and the harm is taken away.

## 8 {-#8}

That which does not make a person worse than he was also does not make his life worse, nor does it harm him either from without or from within.

## 9 {-#9}

The nature of that which is universally useful has been compelled to do this.

## 10 {-#10}

Consider that everything which happens, happens justly, and if you observe carefully, you will find it to be so. I do not say only with respect to the continuity of the series of things, but with respect to what is just, and as if it were done by one who assigns to each thing its value. Observe then as you have begun; and whatever you do, do it in conjunction with this, the being good, and in the sense in which a person is properly understood to be good. Keep to this in every action.

## 11 {-#11}

Do not have such an opinion of things as he has who does you wrong, or such as he wishes you to have, but look at them as they are in truth.

## 12 {-#12}

A person should always have these two rules ready: the one, to do only whatever the reason of the ruling and legislating faculty may suggest for the use of people; the other, to change your opinion, if there is anyone at hand who sets you right and moves you from any opinion. But this change of opinion must proceed only from a certain persuasion, as of what is just or of common advantage, and the like, not because it appears pleasant or brings reputation.

## 13 {-#13}

Do you have reason? I have. Why then don't you use it? For if this does its own work, what else do you wish?

## 14 {-#14}

You have existed as a part. You will disappear in that which produced you; but rather you will be received back into its fundamental principle by transmutation.

## 15 {-#15}

Many grains of frankincense on the same altar: one falls before, another falls after; but it makes no difference.

## 16 {-#16}

Within ten days you will seem a god to those to whom you are now a beast and an ape, if you will return to your principles and the worship of reason.

## 17 {-#17}

Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.

## 18 {-#18}

How much trouble he avoids who does not look to see what his neighbor says or does or thinks, but only to what he does himself, that it may be just and pure; or as Agathon says, look not round at the depraved morals of others, but run straight along the line without deviating from it.

## 19 {-#19}

He who has a vehement desire for posthumous fame does not consider that every one of those who remember him will himself also die very soon; then again also they who have succeeded them, until the whole remembrance shall have been extinguished as it is transmitted through people who foolishly admire and perish. But suppose that those who will remember are even immortal, and that the remembrance will be immortal, what then is this to you? And I say not what is it to the dead, but what is it to the living? What is praise except indeed so far as it has a certain utility? For you now reject unseasonably the gift of nature, clinging to something else...

## 20 {-#20}

Everything which is in any way beautiful is beautiful in itself, and terminates in itself, not having praise as part of itself. Neither worse nor better is a thing made by being praised. I affirm this also of the things which are called beautiful by ordinary people, for example, material things and works of art. That which is really beautiful has no need of anything; not more than law, not more than truth, not more than benevolence or modesty. Which of these things is beautiful because it is praised, or spoiled by being blamed? Is such a thing as an emerald made worse than it was, if it is not praised? Or gold, ivory, purple, a lyre, a little knife, a flower, a shrub?

## 21 {-#21}

If souls continue to exist, how does the air contain them from eternity? But how does the earth contain the bodies of those who have been buried from time so remote? For as here the mutation of these bodies after a certain continuance, whatever it may be, and their dissolution make room for other dead bodies; so the souls which are removed into the air after subsisting for some time are transmuted and diffused, and assume a fiery nature by being received into the seminal intelligence of the universe, and in this way make room for the fresh souls which come to dwell there. And this is the answer which a person might give on the hypothesis of souls continuing to exist. But we must not only think of the number of bodies which are thus buried, but also of the number of animals which are daily eaten by us and the other animals. For what a number is consumed, and thus in a manner buried in the bodies of those who feed on them! And nevertheless this earth receives them by reason of the changes of these bodies into blood, and the transformations into the aerial or the fiery element.

What is the investigation into the truth in this matter? The division into that which is material and that which is the cause of form, the formal.

## 22 {-#22}

Do not be whirled about, but in every movement have respect to justice, and on the occasion of every impression maintain the faculty of comprehension or understanding.

## 23 {-#23}

Everything harmonizes with me, which is harmonious to you, O Universe. Nothing for me is too early nor too late, which is in due time for you. Everything is fruit to me which your seasons bring, O Nature: from you are all things, in you are all things, to you all things return. The poet says, "Dear city of Cecrops"; and will you not say, "Dear city of Zeus"?

## 24 {-#24}

"Occupy yourself with few things," says the philosopher, "if you would be tranquil." But consider if it would not be better to say, "Do what is necessary, and whatever the reason of the animal which is naturally social requires, and as it requires." For this brings not only the tranquility which comes from doing well, but also that which comes from doing few things. For the greatest part of what we say and do being unnecessary, if a person takes this away, he will have more leisure and less uneasiness. Accordingly on every occasion a person should ask himself, "Is this one of the unnecessary things?" Now a person should take away not only unnecessary acts, but also, unnecessary thoughts, for thus superfluous acts will not follow after.

## 25 {-#25}

Try how the life of the good man suits you, the life of him who is satisfied with his portion out of the whole, and satisfied with his own just acts and benevolent disposition.

## 26 {-#26}

Have you seen those things? Look also at these. Do not disturb yourself. Make yourself all simplicity. Does anyone do wrong? It is to himself that he does the wrong. Has anything happened to you? Well; out of the universe from the beginning everything which happens has been apportioned and spun out to you. In a word, your life is short. You must turn to profit the present by the aid of reason and justice. Be sober in your relaxation.

## 27 {-#27}

Either it is a well-arranged universe or a chaos huddled together, but still a universe. But can a certain order subsist in you, and disorder in the All? And this too when all things are so separated and diffused and sympathetic.

## 28 {-#28}

A dark character, a weak character, a stubborn character, beastly, childish, animal, stupid, counterfeit, scurrilous, fraudulent, tyrannical.

## 29 {-#29}

If he is a stranger to the universe who does not know what is in it, no less is he a stranger who does not know what is going on in it. He is a runaway, who flies from social reason; he is blind, who shuts the eyes of the understanding; he is poor, who has need of another, and has not from himself all things which are useful for life. He is an abscess on the universe who withdraws and separates himself from the reason of our common nature through being displeased with the things which happen, for the same nature produces this, and has produced you too: he is a piece torn asunder from the state, who tears his own soul from that of reasonable animals, which is one.

## 30 {-#30}

The one is a philosopher without a tunic, and the other without a book: here is another half naked: "Bread I have not," he says, "and I abide by reason." And "I do not get the means of living out of my learning, and I abide by my reason."

## 31 {-#31}

Love the art, poor as it may be, which you have learned, and be content with it; and pass through the rest of life like one who has entrusted to the gods with his whole soul all that he has, making yourself neither the tyrant nor the slave of any person.

## 32 {-#32}

Consider, for example, the times of Vespasian. You will see all these things: people marrying, bringing up children, sick, dying, warring, feasting, trafficking, cultivating the ground, flattering, obstinately arrogant, suspecting, plotting, wishing for some to die, grumbling about the present, loving, heaping up treasure, desiring consulship, kingly power. Well then, that life of these people no longer exists at all. Again, move to the times of Trajan. Again, all is the same. Their life too is gone. In like manner view also the other epochs of time and of whole nations, and see how many after great efforts soon fell and were resolved into the elements. But chiefly you should think of those whom you have yourself known distracting themselves about idle things, neglecting to do what was in accordance with their proper constitution, and to hold firmly to this and to be content with it. And herein it is necessary to remember that the attention given to everything has its proper value and proportion. For thus you will not be dissatisfied, if you apply yourself to smaller matters no further than is fit.

## 33 {-#33}

The words which were formerly familiar are now antiquated: so also the names of those who were famed of old, are now in a manner antiquated: Camillus, Caeso, Volesus, Leonnatus, and a little after also Scipio and Cato, then Augustus, then also Hadrian and Antoninus. For all things soon pass away and become a mere tale, and complete oblivion soon buries them. And I say this of those who have shone in a wondrous way. For the rest, as soon as they have breathed out their breath, they are gone, and no man speaks of them. And, to conclude the matter, what is even an eternal remembrance? A mere nothing. What then is that about which we ought to employ our serious pains? This one thing: thoughts just, and acts social, and words which never lie, and a disposition which gladly accepts all that happens, as necessary, as usual, as flowing from a principle and source of the same kind.

## 34 {-#34}

Willingly give yourself up to Clotho, one of the Fates, allowing her to spin your thread into whatever things she pleases.

## 35 {-#35}

Everything is only for a day, both that which remembers and that which is remembered.

## 36 {-#36}

Observe constantly that all things take place by change, and accustom yourself to consider that the nature of the Universe loves nothing so much as to change the things which are and to make new things like them. For everything that exists is in a manner the seed of that which will be. But you are thinking only of seeds which are cast into the earth or into a womb: but this is a very ordinary notion.

## 37 {-#37}

You will soon die, and you are not yet simple, not free from disturbances, nor without suspicion of being hurt by external things, nor kindly disposed towards all; nor do you yet place wisdom only in acting justly.

## 38 {-#38}

Examine people's ruling principles, even those of the wise: what kind of things they avoid, and what kind they pursue.

## 39 {-#39}

What is evil to you does not exist in the ruling principle of another; nor yet in any turning and mutation of your physical covering. Where is it then? It is in that part of you in which exists the power of forming opinions about evils. Let this power then not form such opinions, and all is well. And if that which is nearest to it, the poor body, is burnt, filled with matter and rottenness, nevertheless let the part which forms opinions about these things be quiet, that is, let it judge that nothing is either bad or good which can happen equally to the bad man and the good. For that which happens equally to him who lives contrary to nature and to him who lives according to nature, is neither according to nature nor contrary to nature.

## 40 {-#40}

Constantly regard the universe as one living being, having one substance and one soul; and observe how all things have reference to one perception, the perception of this one living being; and how all things act with one movement; and how all things are the cooperating causes of all things which exist; observe too the continuous spinning of the thread and the contexture of the web.

## 41 {-#41}

You are a little soul bearing about a corpse, as Epictetus used to say.

## 42 {-#42}

It is no evil for things to undergo change, and no good for things to continue unchanged as a result of change.

## 43 {-#43}

Time is like a river made up of the events which happen, and a violent stream; for as soon as a thing has been seen, it is carried away, and another comes in its place, and this will be carried away too.

## 44 {-#44}

Everything which happens is as familiar and well known as the rose in spring and the fruit in summer; for such is disease, and death, and calumny, and treachery, and whatever else delights fools or vexes them.

## 45 {-#45}

In the series of things those which follow are always aptly fitted to those which have gone before; for this series is not like a mere enumeration of disjointed things, which has only a necessary sequence, but it is a rational connection: and as all existing things are arranged together harmoniously, so the things which come into existence exhibit no mere succession, but a certain wonderful relationship.

## 46 {-#46}

Always remember the saying of Heraclitus, that the death of earth is to become water, and the death of water is to become air, and the death of air is to become fire, and reversely. And think too of him who forgets where the way leads, and that people quarrel with that with which they are most constantly in communion, the reason which governs the universe; and the things which daily meet with seem to them strange: and consider that we ought not to act and speak as if we were asleep, for even in sleep we seem to act and speak; and that we ought not, like children who learn from their parents, simply to act and speak as we have been taught.

## 47 {-#47}

If any god told you that you would die tomorrow, or certainly the day after tomorrow, you wouldn't care much whether it was on the third day or tomorrow, unless you were in the highest degree mean-spirited—for how small is the difference? So think it no great thing to die after as many years as you can name rather than tomorrow.

## 48 {-#48}

Think continually how many physicians are dead after often contracting their eyebrows over the sick; and how many astrologers after predicting with great pretensions the deaths of others; and how many philosophers after endless discourses on death or immortality; how many heroes after killing thousands; and how many tyrants who have used their power over people's lives with terrible insolence as if they were immortal; and how many cities are entirely dead, so to speak, Helice and Pompeii and Herculaneum, and others innumerable. Add to the reckoning all whom you have known, one after another. One person after burying another has been laid out dead, and another buries him: and all this in a short time. To conclude, always observe how ephemeral and worthless human things are, and what was yesterday a little mucus tomorrow will be a mummy or ashes. Pass then through this little space of time conformably to nature, and end your journey in content, just as an olive falls off when it is ripe, blessing nature who produced it, and thanking the tree on which it grew.

## 49 {-#49}

Be like the promontory against which the waves continually break, but it stands firm and tames the fury of the water around it.

## 50 {-#50}

"Unhappy am I because this has happened to me." Not so, but "Happy am I, though this has happened to me, because I continue free from pain, neither crushed by the present nor fearing the future." For such a thing as this might have happened to every person; but every person would not have continued free from pain on such an occasion. Why then is that rather a misfortune than this a good fortune? And do you in all cases call that a person's misfortune, which is not a deviation from human nature? And does a thing seem to you to be a deviation from human nature, when it is not contrary to the will of human nature? Well, you know the will of nature. Will then this which has happened prevent you from being just, magnanimous, temperate, prudent, secure against inconsiderate opinions and falsehood; will it prevent you from having modesty, freedom, and everything else, by the presence of which human nature obtains all that is its own? Remember too on every occasion which leads you to vexation to apply this principle: not that this is a misfortune, but that to bear it nobly is good fortune.

## 51 {-#51}

It is a common, but still a useful help towards contempt of death, to pass in review those who have tenaciously stuck to life. What more then have they gained than those who have died early? Certainly they lie in their tombs somewhere at last, Cadicianus, Fabius, Julianus, Lepidus, or any one else like them, who have carried out many to be buried, and then were carried out themselves. Altogether the interval is small between birth and death; and consider with how much trouble, and in company with what sort of people and in what a feeble body this interval is laboriously passed. Do not then consider life a thing of any value. For look to the immensity of time behind you, and to the time which is before you, another boundless space. In this infinity then what is the difference between him who lives three days and him who lives three generations?

## 52 {-#52}

Always run to the short way; and the short way is the natural: accordingly say and do everything in conformity with the soundest reason. For such a purpose frees a person from trouble, and warfare, and all artifice and ostentatious display.
